import { Header } from '@/app/components/Header';
import { Footer } from './components/Footer';
import ScrollSearchBar from './components/ScrollSearchbar';
import { db } from './data/db';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header value={"בסייד"}/>
        {children}
        <div className='pb-12'>

          <Footer word={db.default.word} />
        </div>
        </body>
    </html>
  )
}
